title: Dylan Hamme
logo: "/images/Informal_Headshot.jpg"
description: > # your text below (remove <br> elements if you don't need line breaks)
  UMBC 2021, GES Major, Undergrad research assistant.
  <br><br>
  <a href="www.linkedin.com/in/dylanhamme99">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
